<x-templates.admin-template>
    <section class="p-8">
        <h2 class="text-3xl font-bold text-gray-800 mb-6">Welcome to the Admin Dashboard</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <!-- Example Card 1 -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h3 class="text-xl font-semibold mb-4">User Statistics</h3>
                <p class="text-gray-600">View detailed statistics about user registrations and activity.</p>
            </div>
            <!-- Example Card 2 -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h3 class="text-xl font-semibold mb-4">Event Management</h3>
                <p class="text-gray-600">Create, update, and manage events easily from this panel.</p>
            </div>
            <!-- Example Card 3 -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h3 class="text-xl font-semibold mb-4">Reports Overview</h3>
                <p class="text-gray-600">Access and analyze various reports generated by the system.</p>
            </div>
        </div>
    </section>
</x-templates.admin-template>